name: Deploy to Plesk on Interserver

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build React Project
        run: npm run build
        env:
          CI: false

      - name: Copy .htaccess
        run: |
          copy "public\.htaccess" "build\.htaccess"
          copy "public\_redirects" "build\_redirects"
          copy "public\web.config" "build\web.config"

      - name: Deploy to Plesk via FTP
        uses: SamKirkland/ftp-deploy-action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: ./
          dangerous-clean-slate: true
