name: Deploy to Plesk on Interserver

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Install Dependencies
        run: npm install
        
      - name: Build React Project
        run: npm run build
        env:
          VITE_APP_URL: https://dev.earlyagedevelopment.com

      - name: Deploy to Plesk via FTP
        uses: SamKirkland/ftp-deploy-action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: /httpdocs/
          dangerous-clean-slate: true